development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9083b6f913786ae47ba72148772a4a60@porgy.redistogo.com:9255/
  channel_prefix: _hive_production

