meta_product_name: "hiive"
meta_title: "hiive - transform your ugly referal links into a beautiful online store. instantly."
meta_description: "hiive helps creators creators maximise the effectiveness of their existing referral links by transforming boring hyperlinks into beautiful online stores. Now, the products they recommend are showcased and introduced to a whole new audience of potential shoppers. So creators can spend less time selling, and more time making cool shit."
meta_image: "bee.png" # should exist in `app/assets/images/`
twitter_account: "@tristanviney"   # required for Twitter Cards
